export default [
    {
        id: 1,
        title: "PHASE 1",
        heading:"Minting event",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        light: true,
        theme: "card",
        themeContent: "cardContent",
    },
    {
        id: 2,
        title: "PHASE 2",
        heading:"CLAIM PRODUCT",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        light: false,
        theme: "cardTrans",
        themeContent: "cardContentTrans",
    },
    {
        id: 3,
        title: "PHASE 3",
        heading:"AIRDROP",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        light: false,
        theme: "cardTrans",
        themeContent: "cardContentTrans",
    },
    {
        id: 4,
        title: "PHASE 4",
        heading:"BURN",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        light: false,
        theme: "cardTrans",
        themeContent: "cardContentTrans",
    },
]